# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MDGSF
brief-intro: Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mdgsf.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: MDGSF
facebook_username: MDGSF
github_username:  MDGSF
email: 1342042894@qq.com
weibo_username: MDGSF
zhihu_username: MDGSF
linkedIn_username: MDGSF
dribbble_username:

description_footer: 本站记录我开发之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: mdgsf

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 7026a5ee74a186e09616a0a7d900e81f
google_analytics_id: UA-132353685-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins:
  - jekyll-paginate
paginate: 6
